const express = require('express');
const controller = require('../controllers/conversation.controller');
const { authenticate } = require('../middleware/auth.middleware');
const router = express.Router();
router.use(authenticate);
router.get('/', controller.listConversations);
router.post('/', controller.createConversation);
router.get('/:conversationId/messages', controller.listMessages);
router.post('/:conversationId/messages', controller.sendMessage);
router.post('/:conversationId/messages/:messageId/retry', controller.retryMessage);
module.exports = router;
